/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// Provides details about a terminated subscriber session.
type SubscriberHistory struct {
	SubscriberId int32 `json:"subscriber_id,omitempty"`
	// String subscriber_id representation for I-JSON compliance.
	SubscriberIdStr string `json:"subscriber_id_str,omitempty"`
	// The subscriber's user name.
	SubscriberUserName string `json:"subscriber_user_name,omitempty"`
	// Reason why the subscriber session got terminated.
	SubscriberTerminationReason string `json:"subscriber_termination_reason,omitempty"`
	// The accounting session ID.
	AccountingSessionId string `json:"accounting_session_id,omitempty"`
	IfpName             string `json:"ifp_name,omitempty"`
	// The inner VLAN (C-tag) associated with the subscriber.
	InnerVlan int32 `json:"inner_vlan,omitempty"`
	// The outer VLAN (S-tag) associated with the subscriber.
	OuterVlan int32 `json:"outer_vlan,omitempty"`
	// The client MAC address.
	ClientMac  string                `json:"client_mac,omitempty"`
	AccessType *SubscriberAccessType `json:"access_type,omitempty"`
	// The Agent-Remote-ID (ARI).
	AgentRemoteId string `json:"agent_remote_id,omitempty"`
	// The Agent-Circuit-ID (ACI).
	AgentCircuitId string `json:"agent_circuit_id,omitempty"`
}
