/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// PIM interface capabilities
type PimInstanceInterfaceCapabilities struct {
	// Flag that indicates whether Join suppression is disabled (true) or not (false)
	DisableJoinSuppression bool `json:"disable_join_suppression,omitempty"`
	// A flag that indicates whether the designated router (DR) election uses the DR priority.
	UseDesignatedRouterPriority bool `json:"use_designated_router_priority,omitempty"`
	// The effective prune delay interval in milliseconds.
	EffectivePruneDelayInterval int32 `json:"effective_prune_delay_interval,omitempty"`
	// The effective override interval in milliseconds.
	EffectiveOverrideInterval int32 `json:"effective_override_interval,omitempty"`
}
