/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// Dynamic QoS settings.
type L2bsaServiceConfigQos struct {
	// The QoS configuration profile name.
	QosProfileName string `json:"qos_profile_name,omitempty"`
	// The parent scheduler element of the scheduler-map assigned to the subscriber can be selected with this attribute. If not present, the scheduler-map will be directly bound to the corresponding IFP.
	ParentScheduler string `json:"parent_scheduler,omitempty"`
	// Dynamic QoS shaper string which contains a list of multiple shaper settings separated by semicolon.
	Shaper string `json:"shaper,omitempty"`
	// Dynamic QoS policer string which contains a list of multiple policer level settings separated by semicolon.
	Policer string `json:"policer,omitempty"`
	// Dynamic QoS queue string which contains a list of multiple queue sizes separated by semicolon.
	Queue string `json:"queue,omitempty"`
}
