/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

import (
	"time"
)

// RPKI RTR session state.
type RpkirtrSession struct {
	InstanceName string                    `json:"instance_name,omitempty"`
	Timers       *RpkirtrSessionTimers     `json:"timers,omitempty"`
	Statistics   *RpkirtrSessionStatistics `json:"statistics,omitempty"`
	// The session state.
	SessionState string `json:"session_state,omitempty"`
	// The timestamp of the last session state transition.
	LastStateTransition time.Time     `json:"last_state_transition,omitempty"`
	RpkiCache           *RpkirtrCache `json:"rpki_cache,omitempty"`
	// The session preference.
	Preference int `json:"preference,omitempty"`
	// The local IPv4 address.
	Ipv4Address string `json:"ipv4_address,omitempty"`
	// The local IPv6 address.
	Ipv6Address string `json:"ipv6_address,omitempty"`
}
