/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

type Optic struct {
	Lanes   []Lane `json:"lanes,omitempty"`
	IfpName string `json:"ifp_name,omitempty"`
	// The optics serial number.
	SerialNumber string `json:"serial_number,omitempty"`
	// The optics part number.
	PartNumber string `json:"part_number,omitempty"`
	// The optics material number. The material number is a unique identifier for the materials management system.
	MaterialNumber string `json:"material_number,omitempty"`
	// The optics vendor name.
	VendorName string `json:"vendor_name,omitempty"`
	// The optics wave length.
	Wavelength float64 `json:"wavelength,omitempty"`
	// The optics type.
	OpticsType string `json:"optics_type,omitempty"`
	// The optics connector type.
	ConnectorType string `json:"connector_type,omitempty"`
	// The optics power class.
	PowerClass string `json:"power_class,omitempty"`
	// The optics power state class.
	PowerClassState string `json:"power_class_state,omitempty"`
	// The optics manufacturing date.
	DateManufactured string `json:"date_manufactured,omitempty"`
	// The optics voltage supply in volts.
	VoltageV float64 `json:"voltage_v,omitempty"`
	// The optics temperature in degree celsius.
	TemperatureC float64 `json:"temperature_c,omitempty"`
}
