/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// The traceroute parameters
type TracerouteArguments struct {
	// The destination IPv4 or IPv6 address.
	DestinationIp string `json:"destination_ip,omitempty"`
	InstanceName  string `json:"instance_name,omitempty"`
	// The source IPv4 or IPv6 address.
	SourceIp string `json:"source_ip,omitempty"`
	// The logical source interface.
	SourceIfl string `json:"source_ifl,omitempty"`
	// The maximum hops to reach the destination.
	MaxHops string `json:"max_hops,omitempty"`
	// The interval between to packages in seconds.
	Interval float64 `json:"interval,omitempty"`
	// The packet payload size in bytes.
	Size float64 `json:"size,omitempty"`
}
