/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// TX-related state.
type TransceiverLaneTx struct {
	// The status of the Loss-of-Signal (LoS) alert flag.
	LosAlert bool `json:"los_alert,omitempty"`
	// The laser power in milliwatts.
	PowerMw float64 `json:"power_mw,omitempty"`
	// The laser power in dbm.
	PowerDbm float64 `json:"power_dbm,omitempty"`
	// The power high alarm flag.
	PowerHighAlarm bool `json:"power_high_alarm,omitempty"`
	// The power high warning flag.
	PowerHighWarning bool `json:"power_high_warning,omitempty"`
	// The power low alarm flag.
	PowerLowAlarm bool `json:"power_low_alarm,omitempty"`
	// The power low warning flag.
	PowerLowWarning bool `json:"power_low_warning,omitempty"`
	// Laser bias current in mA.
	BiasCurrentMa float64 `json:"bias_current_ma,omitempty"`
	// The bias current high alarm flag.
	BiasCurrentHighAlarm bool `json:"bias_current_high_alarm,omitempty"`
	// The bias current high warning flag.
	BiasCurrentHighWarning bool `json:"bias_current_high_warning,omitempty"`
	// The bias current low alarm flag.
	BiasCurrentLowAlarm bool `json:"bias_current_low_alarm,omitempty"`
	// The bias current low warning flag.
	BiasCurrentLowWarning bool `json:"bias_current_low_warning,omitempty"`
}
