/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// The BGP timers.
type BgpInstanceTimers struct {
	// Graceful restart (GR) stale timer value in seconds.
	GrStaleTime int32 `json:"gr_stale_time,omitempty"`
	// Graceful restart (GR) purge timer value in seconds.
	GrPurgeTime int32 `json:"gr_purge_time,omitempty"`
	// Graceful restart (GR) restart timer value in seconds.
	GrRestartTime int32 `json:"gr_restart_time,omitempty"`
	// BGP hold timer value in seconds. A BGP peer is considered down if the hold timer expires before receiving keep-alive messages from the BGP peer.  Every received hello message resets the hold timer.
	HoldTime int32 `json:"hold_time,omitempty"`
	// BGP keep-alive timer value methods in seconds. The router sends a hello message to a peer when the keep-alive timer expires.
	KeepAliveTime int32 `json:"keep_alive_time,omitempty"`
	// BGP connect timer value in seconds. An active BGP peering tries to establish the peering every bgp_connect_time seconds.
	ConnectTime int32 `json:"connect_time,omitempty"`
}
