/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// The optical lane information.
type Lane struct {
	// The lane ID.
	LaneId int `json:"lane_id,omitempty"`
	// The optic temperature in degree celsius.  **Deprecated**. Moved to the optic because the temperature value exists for the entire optic rather than per lane.
	TemperatureCelsius float64 `json:"temperature_celsius,omitempty"`
	// The optic temperature in degree celsius.  **Deprecated**. Moved to the optic because the voltage exists for the entire optic rather than per lane.
	Voltage float64 `json:"voltage,omitempty"`
	Tx      *LaneTx `json:"tx,omitempty"`
	Rx      *LaneRx `json:"rx,omitempty"`
}
