/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// IS-IS timers.
type IsisInstanceTimers struct {
	// The hold time in seconds. A neighbor is considered down if no hello message is received from the neighbor before the hold time expires. The keep-alive interval for sending hello messages is derived from the hold time (keep-alive = hold / 3).
	HoldTime int32 `json:"hold_time,omitempty"`
	// The overload interval in seconds. A router in overload state resets the overload flag when the overload time is expired.
	OverloadTime int32 `json:"overload_time,omitempty"`
}
