/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// Test subscriber
type TestAaaObject struct {
	// Subscriber ID.
	SubscriberId int32 `json:"subscriber_id"`
	// Name of the access profile.
	AccessProfileName string `json:"access_profile_name"`
	// Name of the AAA profile.
	AaaProfileName string `json:"aaa_profile_name"`
	// Username of the subscriber.
	SubscriberUserName string `json:"subscriber_user_name,omitempty"`
	// Password of the subscriber.
	Password string `json:"password,omitempty"`
	// Interface of the subscriber. *WARNING*: This attribute is deprecated. Please use <code>ifp_name</code> instead.
	InterfaceName string `json:"interface_name,omitempty"`
	// Mocked physical subscriber interface.
	IfpName string `json:"ifp_name,omitempty"`
	// The Agent-Remote-ID (ARI).
	AgentRemoteId string `json:"agent_remote_id,omitempty"`
	// The Agent-Circuit-ID (ACI).
	AgentCircuitId string `json:"agent_circuit_id,omitempty"`
	// Outer VLAN value.
	OuterVlan int32 `json:"outer_vlan,omitempty"`
	// Inner VLAN value.
	InnerVlan int32 `json:"inner_vlan,omitempty"`
	// MAC address of the subscriber.
	ClientMac string `json:"client_mac,omitempty"`
}
