/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// A flowspec rule and its implementation status.
type FlowspecRule struct {
	// The unique rule hash value.
	RuleHash string `json:"rule_hash,omitempty"`
	// The rule priority.
	RulePriority int `json:"rule_priority,omitempty"`
	// Whether this rule is applied or not. A rule might not be applicable due to hardware restrictions. These rules are still advertised to all other BGP peers with negotiated flowspec address family.
	Applied bool `json:"applied,omitempty"`
	// The number of implemented ACLs.
	AclCount int `json:"acl_count,omitempty"`
	// Detailed status of this flowspec rule.
	FlowspecStatus string             `json:"flowspec_status,omitempty"`
	Match          *FlowspecRuleMatch `json:"match,omitempty"`
	// The actions executed by this rule.
	Actions []string `json:"actions,omitempty"`
}
