/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// Transceiver module details.
type TransceiverModuleInfo struct {
	IfpName string `json:"ifp_name,omitempty"`
	// The optics serial number.
	SerialNumber string `json:"serial_number,omitempty"`
	// The optics part number.
	PartNumber string `json:"part_number,omitempty"`
	// The optics material number. The material number is a unique identifier for the materials management system.
	MaterialNumber string `json:"material_number,omitempty"`
	// The transceiver vendor name.
	VendorName string `json:"vendor_name,omitempty"`
	// The transceiver wavelength.
	Wavelength float64 `json:"wavelength,omitempty"`
	// The transceiver type.
	TransceiverType string `json:"transceiver_type,omitempty"`
	// The transceiver capabilities.
	TransceiverCapabilities string `json:"transceiver_capabilities,omitempty"`
	// The optics connector type.
	ConnectorType string `json:"connector_type,omitempty"`
	// The optics power class.
	PowerClass int `json:"power_class,omitempty"`
	// The power class rating.
	PowerClassRating string `json:"power_class_rating,omitempty"`
	// The power mode.
	PowerMode string `json:"power_mode,omitempty"`
	// The manufacturing date.
	DateManufactured string `json:"date_manufactured,omitempty"`
}
