/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// Subscriber QoS policer settings.
type SubscriberQosPolicer struct {
	// The committed information rate (CIR) in kbps.
	CirKbps int32 `json:"cir_kbps,omitempty"`
	// The comitted burst size (CBS) in kbps.
	CbsKbps int32 `json:"cbs_kbps,omitempty"`
	// The peak information rate (PIR) in kbps.
	PirKbps int32 `json:"pir_kbps,omitempty"`
	// The peak burst size (PBS) in kbps.
	PbsKbps int32 `json:"pbs_kbps,omitempty"`
}
