/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// The arguments of the executed ping command.
type PingArguments struct {
	// The pinged destination IP address (ICMP ping).
	DestinationIp string `json:"destination_ip,omitempty"`
	// The pinged destination IP FEC (LSPING).
	DestincationIpFec string `json:"destincation_ip_fec,omitempty"`
	// The FEC type (LSPING).
	FecType string `json:"fec_type,omitempty"`
	// The source IP address.
	SourceIp string `json:"source_ip,omitempty"`
	// The egress interface name (ICMP ping).
	SourceIfl string `json:"source_ifl,omitempty"`
	// The routing instance name.
	InstanceName string `json:"instance_name,omitempty"`
	// The interval between two pings.
	Interval float32 `json:"interval,omitempty"`
	// The number of pings sent.
	Count int `json:"count,omitempty"`
	// The packet size in bytes.
	Size int `json:"size,omitempty"`
	// The IP TTL value (ICMP ping).
	Ttl int `json:"ttl,omitempty"`
	// The IP ToS value (ICMP ping).
	Tos int `json:"tos,omitempty"`
}
