/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

type RpkirtrSessionTimers struct {
	// The connect timer interval in seconds.
	ConnectTime int `json:"connect_time,omitempty"`
	// The remaining time in seconds until the connect timer fires.
	ConnectTimer int `json:"connect_timer,omitempty"`
	// The refresh timer interval in seconds.
	RefreshTime int `json:"refresh_time,omitempty"`
	// The remaining time in seconds until the refresh timer fires.
	RefreshTimer int `json:"refresh_timer,omitempty"`
	// The retry timer interval in seconds.
	RetryTime int `json:"retry_time,omitempty"`
	// The remaining time in seconds until the retry timer fires.
	RetryTimer int `json:"retry_timer,omitempty"`
	// The record expiry timer interval in seconds.
	RecordExpiryTime int `json:"record_expiry_time,omitempty"`
	// The remaining time in seconds until the record expiry timer fires.
	RecordExpiryTimer int `json:"record_expiry_timer,omitempty"`
}
