/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

import (
	"time"
)

// IS-IS neighbor details.
type IsisNeighbor struct {
	// The IS-IS adjacency state.
	IsisAdjacencyState string `json:"isis_adjacency_state,omitempty"`
	// Last state transition time.
	LastStateTransition time.Time `json:"last_state_transition,omitempty"`
	// The IS-IS adjacency type.
	IsisAdjacencyType string `json:"isis_adjacency_type,omitempty"`
	// The IS-IS level(s) the adjacency belongs too.
	Level   string `json:"level,omitempty"`
	IflName string `json:"ifl_name,omitempty"`
	// Local IPv4 address.
	Ipv4Address string `json:"ipv4_address,omitempty"`
	// Local IPv6 address.
	Ipv6Address string                  `json:"ipv6_address,omitempty"`
	Neighbor    *IsisNeighborNeighbor   `json:"neighbor,omitempty"`
	Timers      *IsisNeighborTimers     `json:"timers,omitempty"`
	Statistics  *IsisNeighborStatistics `json:"statistics,omitempty"`
}
