/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// BGP best-route selection flags and default values.
type BgpInstanceRouteSelection struct {
	// A constant BGP multi exit discriminator (MED) value shared as metric with all peers.  The metric is derived from the IGP if not specified.
	Med int32 `json:"med,omitempty"`
	// The AS-local preference value of this router. The router with the highest local preference  is preferred for routing traffic to an external AS if multiple paths exist.
	LocalPreference int32 `json:"local_preference,omitempty"`
	// The preference value for IBGP routes,  i.e. routes learned from BGP peers in the same AS.
	IbgpPreference int32 `json:"ibgp_preference,omitempty"`
	// The preference value for EBGP routes,  i.e. routes learned from BGP peers in an external AS.
	EbgpPreference int32 `json:"ebgp_preference,omitempty"`
	// Ignore ASN when comparing MED values for route selection.
	AlwaysCompareMed bool `json:"always_compare_med,omitempty"`
	// Ignore AS path length for route selection.
	IgnoreAsPathLength bool `json:"ignore_as_path_length,omitempty"`
	// Ignore local preference for route selection.
	IgnoreLocalPref bool `json:"ignore_local_pref,omitempty"`
	// Ignore route source for route selection.
	IgnoreRouteSource bool `json:"ignore_route_source,omitempty"`
	// Ignore origin for route selection.
	IgnoreOrigin bool `json:"ignore_origin,omitempty"`
	// Ignore MED for route selection. bgp_always_compe_med has no effect if bgp_ignore_med is set to true.
	IgnoreMed bool `json:"ignore_med,omitempty"`
	// Ignore route type for route selection.
	IgnoreRouteType bool `json:"ignore_route_type,omitempty"`
	// Ignore up-time for route selection.
	IgnoreUpTime bool `json:"ignore_up_time,omitempty"`
	// Ignore route ID for route selection.
	IgnoreRouterId bool `json:"ignore_router_id,omitempty"`
	// Ignore cluster length for route selection.
	IgnoreClusterLength bool `json:"ignore_cluster_length,omitempty"`
	// Ignore peer IP for route selection.
	IgnorePeerIp bool `json:"ignore_peer_ip,omitempty"`
}
