/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

type Transceiver struct {
	Lanes   []TransceiverLane `json:"lanes,omitempty"`
	IfpName string            `json:"ifp_name,omitempty"`
	// The optics serial number.
	SerialNumber string `json:"serial_number,omitempty"`
	// The optics part number.
	PartNumber string `json:"part_number,omitempty"`
	// The optics material number. The material number is a unique identifier for the materials management system.
	MaterialNumber string `json:"material_number,omitempty"`
	// The transceiver vendor name.
	VendorName string `json:"vendor_name,omitempty"`
	// The transceiver wavelength.
	Wavelength float64 `json:"wavelength,omitempty"`
	// The transceiver type.
	TransceiverType string `json:"transceiver_type,omitempty"`
	// The transceiver capabilities.
	TransceiverCapabilities string `json:"transceiver_capabilities,omitempty"`
	// The optics connector type.
	ConnectorType string `json:"connector_type,omitempty"`
	// The optics power class.
	PowerClass string `json:"power_class,omitempty"`
	// The power state class. This attribute has been marked deprecated and will be removed in a future release. Please use the power_class_mode attribute instead.
	PowerClassState string `json:"power_class_state,omitempty"`
	// The power class mode.
	PowerClassMode string `json:"power_class_mode,omitempty"`
	// The manufacturing date.
	DateManufactured string `json:"date_manufactured,omitempty"`
	// The voltage supply in volts.
	VoltageV float64 `json:"voltage_v,omitempty"`
	// The voltage high alarm threshold in volts
	VoltageHighAlarmThresholdV float64 `json:"voltage_high_alarm_threshold_v,omitempty"`
	// The voltage high warning threshold in volts.
	VoltageHighWarningThresholdV float64 `json:"voltage_high_warning_threshold_v,omitempty"`
	// The voltage low alarm threshold in volts.
	VoltageLowAlarmThresholdV float64 `json:"voltage_low_alarm_threshold_v,omitempty"`
	// The voltage low warning threshold in volts.
	VoltageLowWarningThresholdV float64 `json:"voltage_low_warning_threshold_v,omitempty"`
	// The transceiver temperature in degree celsius.
	TemperatureC float64 `json:"temperature_c,omitempty"`
	// The temperature high alarm threshold in degree celsius.
	TemperatureHighAlarmThresholdV float64 `json:"temperature_high_alarm_threshold_v,omitempty"`
	// The temperature high warning threshold in degree celsius.
	TemperatureHighWarningThresholdV float64 `json:"temperature_high_warning_threshold_v,omitempty"`
	// The temperature low alarm threshold in degree celsius.
	TemperatureLowAlarmThresholdV float64 `json:"temperature_low_alarm_threshold_v,omitempty"`
	// The temperatue low warning threshold in degree celsius.
	TemperatureLowWarningThresholdV float64              `json:"temperature_low_warning_threshold_v,omitempty"`
	Tx                              *TransceiverModuleTx `json:"tx,omitempty"`
	Rx                              *TransceiverModuleRx `json:"rx,omitempty"`
}
