/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

type Ospfv3Interface struct {
	IflName string `json:"ifl_name,omitempty"`
	// The OSPF area to which the interface belongs.
	AreaId string `json:"area_id,omitempty"`
	// The state of the OSPF interface.
	OspfIflState string `json:"ospf_ifl_state,omitempty"`
	// The OSPF interface type.
	OspfIflType string `json:"ospf_ifl_type,omitempty"`
	// Number of neighbors on the OSPF interface.
	FullNeighbors int `json:"full_neighbors,omitempty"`
	// The interface OSPF metric value.
	Metric int `json:"metric,omitempty"`
	// The IPv6 address of the interface in CIDR notation.
	Ipv6Prefix string `json:"ipv6_prefix,omitempty"`
	// The OSPF protocol MTU.
	Ipv6Mtu int `json:"ipv6_mtu,omitempty"`
	// OSPF priority on the interface.
	Priority int `json:"priority,omitempty"`
	// The designated router on the interface.
	DesignatedRouter string `json:"designated_router,omitempty"`
	// The backup designated router on the interface.
	BackupDesignatedRouter string `json:"backup_designated_router,omitempty"`
	// OSPF hello interval on the interface.
	HelloInterval int `json:"hello_interval,omitempty"`
	// OSPF dead interval on the interface.
	DeadInterval int `json:"dead_interval,omitempty"`
	// The segment routing index on the interface.
	SegmentRoutingIndex int `json:"segment_routing_index,omitempty"`
	// The authentication type on the interface.
	AuthenticationType string `json:"authentication_type,omitempty"`
}
