/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// Set of configured BGP capabilities.
type BgpInstanceCapabilities struct {
	// Accept 4-byte ASN numbers.
	As4Capable bool `json:"as4_capable,omitempty"`
	// Resend all prefixes if a peer asks for it.
	RouteRefreshCapable bool `json:"route_refresh_capable,omitempty"`
	// Preserve forwarding state during BGP restart.
	GracefulRestartCapable bool `json:"graceful_restart_capable,omitempty"`
	// Reject all routes from eBGP peers if the peer does not add its AS  as first AS in the AS path.
	EnforceFirstAs bool `json:"enforce_first_as,omitempty"`
}
