/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// Collection of IS-IS error counters maintained for this neighbor adjacency.
type IsisNeighborStatistics struct {
	// Total number of state transitions.
	StateTransitionCount int32 `json:"state_transition_count,omitempty"`
	// Information why the adjacency was down last time.
	LastDownReason string `json:"last_down_reason,omitempty"`
	// Since when this adjacency is UP.
	UpTime string `json:"up_time,omitempty"`
	// Count of adjacency down due to level mismatch
	LevelMismatchErrorCount int32 `json:"level_mismatch_error_count,omitempty"`
	// Count of adjacency down due to area mismatch.
	AreaMismatchErrorCount int32 `json:"area_mismatch_error_count,omitempty"`
	// Count of adjacency down due to system ID mismatch.
	SystemIdErrorCount int32 `json:"system_id_error_count,omitempty"`
	// Count of adjacency down due to subnet mismatch.
	SubnetMismatchErrorCount int32 `json:"subnet_mismatch_error_count,omitempty"`
	// Count of adjacency down due to hold time expiry.
	HoldTimeoutErrorCount int32 `json:"hold_timeout_error_count,omitempty"`
	// Count of adjacency down due to neighbor down.
	NeighborDownErrorCount int32 `json:"neighbor_down_error_count,omitempty"`
	// Count of adjacency down due to interface down.
	IflDownErrorCount int32 `json:"ifl_down_error_count,omitempty"`
	// Count of adjacency down due to interaface config.
	IflConfigErrorCount int32 `json:"ifl_config_error_count,omitempty"`
	// Count of adjacency down due to reset from CLI.
	AdminResetCount int32 `json:"admin_reset_count,omitempty"`
	// Count of adjacency down due to area config.
	AreaConfigErrorCount int32 `json:"area_config_error_count,omitempty"`
	// Count of adjacency down due to other errors.
	OtherErrorCount int32 `json:"other_error_count,omitempty"`
	// Count of received hello messages.
	ReceivedKeepAliveCount int32 `json:"received_keep_alive_count,omitempty"`
}
