/*
 * RBFS Operational State API
 *
 * This contract describes the RBFS Operational State API contract defined by RBMS, the RtBrick Management System. This API is a _consumer-driven_ API, which means that all changes to this API **must be approved** by RBMS, the consumer of this API to avoid compatibility issues.  The API is kept backwards-compatible and anyone is allowed to _use_ this API.  The consumer of the API _must_ ignore additional attributes not explained in this specification. Additional attributes are _not_ considered violating backwards compatibility. In contrary, additional attributes allow extending the API while preserving backward compatibility.
 *
 * API version: 1.0.0
 * Contact: martin@rtbrick.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package state

// OSPF neighbor details.
type Ospfv3Neighbor struct {
	// The OSPF neighbor state.
	OspfNeighborState string `json:"ospf_neighbor_state,omitempty"`
	// The area in which the neighbor resides.
	AreaId  string `json:"area_id,omitempty"`
	IflName string `json:"ifl_name,omitempty"`
	// The local IPv6 address of the neighborship.
	Ipv6Address string `json:"ipv6_address,omitempty"`
	// The designated router on the neighbor interface.
	DesignatedRouter string `json:"designated_router,omitempty"`
	// The backup designated router on the neighbor interface.
	BackupDesignatedRouter string                  `json:"backup_designated_router,omitempty"`
	Neighbor               *Ospfv3NeighborNeighbor `json:"neighbor,omitempty"`
}
